WIP
uclouvain/osis-signature pull request #2
Opened 2021-06-21 10:33 UTC by SebCorbin

2021-06-21 11:55 UTC, albrugnetti commented on domain.py
> +        return all(value for field, value in self.__dict__.items() if field != 'person')
Est-ce que tu n'aurais pas deux sous-type d'acteur ? ExternalActor / UCLouvainActor?

2021-06-21 11:55 UTC, albrugnetti commented on contrib/widgets.py
> +                return [Actor.from_model(actor).__dict__ for actor in actors]
Est-ce qu'il est possible d'avoir une fonction dans **ActorModel**

```python
def fetch_actors(process_id: str) -> List[Actor]:
  XXX 
```
qui contient ce code

2021-06-21 12:34 UTC, SebCorbin commented on domain.py
> +        return all(value for field, value in self.__dict__.items() if field != 'person')
C'est compliqué à gérer, car les données sont de la même source (formulaire) et sont enregistrées dans le même modèle, mais si tu me dis en quoi ça aiderait le code, je suis pour :)

Autre chose : plus ça va plus je pense que je vais supprimer `Actor` de `domain` car je pense pouvoir faire sans

2021-07-09 07:57 UTC, SebCorbin commented
@albrugnetti `field_ref` ne semble plus utilisé, je l'ai laissé pour le moment mais si tu approuve, je le retire avant de merger

2021-07-09 08:11 UTC, albrugnetti requested changes

2021-07-09 08:11 UTC, albrugnetti commented on README.md
> +    return render(request, "send_invite.html", {'form': form, 'actor': actor})
Est-il possible d'écrire la view au format Class Based View ? 
Dans OSIS, on privilégie la structure en Classe plutôt qu'en fonction

2021-07-09 08:11 UTC, albrugnetti commented on README.md
> +    return render(request, "sign.html", {'form': form, 'actor': actor})
Idem

2021-07-09 08:11 UTC, albrugnetti commented on contrib/forms.py
> +class ExternalActorForm(EmptyPermittedForm, forms.ModelForm):
Pourquoi d'une classe à l'autre l'ordre **EmptyPermittedForm** est différent?

2021-07-09 08:11 UTC, albrugnetti commented on models.py
> +        ).exists()
Est-ce que tu ne peux pas utiliser ton lookup? **all_signed** ?

2021-07-09 08:15 UTC, SebCorbin commented on models.py
> +        ).exists()
Non car le lookup est sur la ForeignKey de Process, et là je suis dans un queryset d'Actor, ils sont complémentaires

2021-07-09 08:16 UTC, SebCorbin commented on contrib/forms.py
> +class ExternalActorForm(EmptyPermittedForm, forms.ModelForm):
Bien vu 👍

2021-07-09 08:59 UTC, albrugnetti approved these changes

2021-07-09 09:25 UTC, merged